server:
  port: 18080

errMsg:
  12001: ["BSS_RET_ERR", "获取bss数据失败"]

spring:
  application:
    name: http-servlet-test
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    lettuce:  # Spring Boot 2.0 配置
      pool:
        max-active: 15
        max-wait: 500
        max-idle: 10
        min-idle: 5